AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-jenkins-demo-app

  Sample SAM Template for sam-jenkins-demo-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  FunctionName:
    Type: String 
  LambdaAlias:
    Type: String
    Default: DEV
  AutoPublishCodeSha:
    Type: String           
Globals:
  Function:
    Timeout: 3
Resources:
  CMPInfrastructureServiceLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CMP-Infrastructure-service-lambda/
      Handler: app.lambdaHandler
      FunctionName: !Ref FunctionName
      Runtime: nodejs12.x
      AutoPublishAlias: !Ref LambdaAlias
      AutoPublishCodeSha256: !Ref AutoPublishCodeSha
      DeploymentPreference:
       Type: AllAtOnce

Outputs:
  CMPInfrastructureServiceLambda:
    Description: "CMPInfrastructureServiceLambda Lambda Function ARN"
    Value: !GetAtt CMPInfrastructureServiceLambda.Arn
  CMPInfrastructureServiceLambdaIamRole:
    Description: "Implicit IAM Role created for CMPInfrastructureServiceLambda"
    Value: !GetAtt CMPInfrastructureServiceLambdaRole.Arn
